// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proxy/selector/config.proto

package selector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Match         string                 `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	HandlerTag    string                 `protobuf:"bytes,3,opt,name=handler_tag,json=handlerTag,proto3" json:"handler_tag,omitempty"`
	LoopbackAddr  string                 `protobuf:"bytes,4,opt,name=loopback_addr,json=loopbackAddr,proto3" json:"loopback_addr,omitempty"`     // e.g. "127.0.0.1:10001"; if empty, resolved from handler's receiver config
	ProxyProtocol uint32                 `protobuf:"varint,5,opt,name=proxy_protocol,json=proxyProtocol,proto3" json:"proxy_protocol,omitempty"` // 0 = off, 1 = PROXY protocol v1, 2 = PROXY protocol v2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proxy_selector_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_selector_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proxy_selector_config_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetMatch() string {
	if x != nil {
		return x.Match
	}
	return ""
}

func (x *Rule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Rule) GetHandlerTag() string {
	if x != nil {
		return x.HandlerTag
	}
	return ""
}

func (x *Rule) GetLoopbackAddr() string {
	if x != nil {
		return x.LoopbackAddr
	}
	return ""
}

func (x *Rule) GetProxyProtocol() uint32 {
	if x != nil {
		return x.ProxyProtocol
	}
	return 0
}

type Config struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Rules             []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	DefaultHandlerTag string                 `protobuf:"bytes,2,opt,name=default_handler_tag,json=defaultHandlerTag,proto3" json:"default_handler_tag,omitempty"`
	ReadSize          int32                  `protobuf:"varint,3,opt,name=read_size,json=readSize,proto3" json:"read_size,omitempty"`                  // Max peek buffer size in bytes (default 2048)
	PeekTimeoutMs     int32                  `protobuf:"varint,4,opt,name=peek_timeout_ms,json=peekTimeoutMs,proto3" json:"peek_timeout_ms,omitempty"` // Peek timeout in milliseconds (default 5000)
	MinPeekSize       int32                  `protobuf:"varint,5,opt,name=min_peek_size,json=minPeekSize,proto3" json:"min_peek_size,omitempty"`       // Min bytes before detection proceeds (default 16)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_selector_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_selector_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_selector_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Config) GetDefaultHandlerTag() string {
	if x != nil {
		return x.DefaultHandlerTag
	}
	return ""
}

func (x *Config) GetReadSize() int32 {
	if x != nil {
		return x.ReadSize
	}
	return 0
}

func (x *Config) GetPeekTimeoutMs() int32 {
	if x != nil {
		return x.PeekTimeoutMs
	}
	return 0
}

func (x *Config) GetMinPeekSize() int32 {
	if x != nil {
		return x.MinPeekSize
	}
	return 0
}

var File_proxy_selector_config_proto protoreflect.FileDescriptor

const file_proxy_selector_config_proto_rawDesc = "" +
	"\n" +
	"\x1bproxy/selector/config.proto\x12\x13xray.proxy.selector\"\xa3\x01\n" +
	"\x04Rule\x12\x14\n" +
	"\x05match\x18\x01 \x01(\tR\x05match\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x1f\n" +
	"\vhandler_tag\x18\x03 \x01(\tR\n" +
	"handlerTag\x12#\n" +
	"\rloopback_addr\x18\x04 \x01(\tR\floopbackAddr\x12%\n" +
	"\x0eproxy_protocol\x18\x05 \x01(\rR\rproxyProtocol\"\xd2\x01\n" +
	"\x06Config\x12/\n" +
	"\x05rules\x18\x01 \x03(\v2\x19.xray.proxy.selector.RuleR\x05rules\x12.\n" +
	"\x13default_handler_tag\x18\x02 \x01(\tR\x11defaultHandlerTag\x12\x1b\n" +
	"\tread_size\x18\x03 \x01(\x05R\breadSize\x12&\n" +
	"\x0fpeek_timeout_ms\x18\x04 \x01(\x05R\rpeekTimeoutMs\x12\"\n" +
	"\rmin_peek_size\x18\x05 \x01(\x05R\vminPeekSizeB[\n" +
	"\x17com.xray.proxy.selectorP\x01Z(github.com/xtls/xray-core/proxy/selector\xaa\x02\x13Xray.Proxy.Selectorb\x06proto3"

var (
	file_proxy_selector_config_proto_rawDescOnce sync.Once
	file_proxy_selector_config_proto_rawDescData []byte
)

func file_proxy_selector_config_proto_rawDescGZIP() []byte {
	file_proxy_selector_config_proto_rawDescOnce.Do(func() {
		file_proxy_selector_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_selector_config_proto_rawDesc), len(file_proxy_selector_config_proto_rawDesc)))
	})
	return file_proxy_selector_config_proto_rawDescData
}

var file_proxy_selector_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proxy_selector_config_proto_goTypes = []any{
	(*Rule)(nil),   // 0: xray.proxy.selector.Rule
	(*Config)(nil), // 1: xray.proxy.selector.Config
}
var file_proxy_selector_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.selector.Config.rules:type_name -> xray.proxy.selector.Rule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_selector_config_proto_init() }
func file_proxy_selector_config_proto_init() {
	if File_proxy_selector_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_selector_config_proto_rawDesc), len(file_proxy_selector_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_selector_config_proto_goTypes,
		DependencyIndexes: file_proxy_selector_config_proto_depIdxs,
		MessageInfos:      file_proxy_selector_config_proto_msgTypes,
	}.Build()
	File_proxy_selector_config_proto = out.File
	file_proxy_selector_config_proto_goTypes = nil
	file_proxy_selector_config_proto_depIdxs = nil
}
