// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proxy/whatsapp/config.proto

package whatsapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Target identifies which WhatsApp upstream a connection should be sent to.
type Target int32

const (
	Target_TARGET_UNSPECIFIED Target = 0
	Target_TARGET_CHAT        Target = 1
	Target_TARGET_MEDIA       Target = 2
)

// Enum value maps for Target.
var (
	Target_name = map[int32]string{
		0: "TARGET_UNSPECIFIED",
		1: "TARGET_CHAT",
		2: "TARGET_MEDIA",
	}
	Target_value = map[string]int32{
		"TARGET_UNSPECIFIED": 0,
		"TARGET_CHAT":        1,
		"TARGET_MEDIA":       2,
	}
)

func (x Target) Enum() *Target {
	p := new(Target)
	*p = x
	return p
}

func (x Target) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_whatsapp_config_proto_enumTypes[0].Descriptor()
}

func (Target) Type() protoreflect.EnumType {
	return &file_proxy_whatsapp_config_proto_enumTypes[0]
}

func (x Target) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Target.Descriptor instead.
func (Target) EnumDescriptor() ([]byte, []int) {
	return file_proxy_whatsapp_config_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Upstream for chat (XMPP/Noise) traffic. Default: chatd.whatsapp.net.
	ChatHost string `protobuf:"bytes,1,opt,name=chat_host,json=chatHost,proto3" json:"chat_host,omitempty"`
	ChatPort uint32 `protobuf:"varint,2,opt,name=chat_port,json=chatPort,proto3" json:"chat_port,omitempty"`
	// Upstream for media traffic. Default: media.fmnl3-1.fna.whatsapp.net (a
	// representative cdn host; usually overridden via routing rules or DNS).
	MediaHost string `protobuf:"bytes,3,opt,name=media_host,json=mediaHost,proto3" json:"media_host,omitempty"`
	MediaPort uint32 `protobuf:"varint,4,opt,name=media_port,json=mediaPort,proto3" json:"media_port,omitempty"`
	// Ports that should be routed to the chat upstream by default.
	ChatPorts []uint32 `protobuf:"varint,5,rep,packed,name=chat_ports,json=chatPorts,proto3" json:"chat_ports,omitempty"`
	// Ports that should be routed to the media upstream by default.
	MediaPorts []uint32 `protobuf:"varint,6,rep,packed,name=media_ports,json=mediaPorts,proto3" json:"media_ports,omitempty"`
	// If true, on connections to a chat_port that looks like TLS (443/8443/...),
	// peek the ClientHello and route by SNI: any *.cdn.whatsapp.net SNI goes to
	// media, everything else to chat.
	SniffSni bool `protobuf:"varint,7,opt,name=sniff_sni,json=sniffSni,proto3" json:"sniff_sni,omitempty"`
	// Fallback target when neither port nor SNI matches. Default: TARGET_CHAT.
	DefaultTarget Target `protobuf:"varint,8,opt,name=default_target,json=defaultTarget,proto3,enum=xray.proxy.whatsapp.Target" json:"default_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_whatsapp_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_whatsapp_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_whatsapp_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetChatHost() string {
	if x != nil {
		return x.ChatHost
	}
	return ""
}

func (x *Config) GetChatPort() uint32 {
	if x != nil {
		return x.ChatPort
	}
	return 0
}

func (x *Config) GetMediaHost() string {
	if x != nil {
		return x.MediaHost
	}
	return ""
}

func (x *Config) GetMediaPort() uint32 {
	if x != nil {
		return x.MediaPort
	}
	return 0
}

func (x *Config) GetChatPorts() []uint32 {
	if x != nil {
		return x.ChatPorts
	}
	return nil
}

func (x *Config) GetMediaPorts() []uint32 {
	if x != nil {
		return x.MediaPorts
	}
	return nil
}

func (x *Config) GetSniffSni() bool {
	if x != nil {
		return x.SniffSni
	}
	return false
}

func (x *Config) GetDefaultTarget() Target {
	if x != nil {
		return x.DefaultTarget
	}
	return Target_TARGET_UNSPECIFIED
}

var File_proxy_whatsapp_config_proto protoreflect.FileDescriptor

const file_proxy_whatsapp_config_proto_rawDesc = "" +
	"\n" +
	"\x1bproxy/whatsapp/config.proto\x12\x13xray.proxy.whatsapp\"\xa1\x02\n" +
	"\x06Config\x12\x1b\n" +
	"\tchat_host\x18\x01 \x01(\tR\bchatHost\x12\x1b\n" +
	"\tchat_port\x18\x02 \x01(\rR\bchatPort\x12\x1d\n" +
	"\n" +
	"media_host\x18\x03 \x01(\tR\tmediaHost\x12\x1d\n" +
	"\n" +
	"media_port\x18\x04 \x01(\rR\tmediaPort\x12\x1d\n" +
	"\n" +
	"chat_ports\x18\x05 \x03(\rR\tchatPorts\x12\x1f\n" +
	"\vmedia_ports\x18\x06 \x03(\rR\n" +
	"mediaPorts\x12\x1b\n" +
	"\tsniff_sni\x18\a \x01(\bR\bsniffSni\x12B\n" +
	"\x0edefault_target\x18\b \x01(\x0e2\x1b.xray.proxy.whatsapp.TargetR\rdefaultTarget*C\n" +
	"\x06Target\x12\x16\n" +
	"\x12TARGET_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTARGET_CHAT\x10\x01\x12\x10\n" +
	"\fTARGET_MEDIA\x10\x02B*Z(github.com/xtls/xray-core/proxy/whatsappb\x06proto3"

var (
	file_proxy_whatsapp_config_proto_rawDescOnce sync.Once
	file_proxy_whatsapp_config_proto_rawDescData []byte
)

func file_proxy_whatsapp_config_proto_rawDescGZIP() []byte {
	file_proxy_whatsapp_config_proto_rawDescOnce.Do(func() {
		file_proxy_whatsapp_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_whatsapp_config_proto_rawDesc), len(file_proxy_whatsapp_config_proto_rawDesc)))
	})
	return file_proxy_whatsapp_config_proto_rawDescData
}

var file_proxy_whatsapp_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_whatsapp_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_whatsapp_config_proto_goTypes = []any{
	(Target)(0),    // 0: xray.proxy.whatsapp.Target
	(*Config)(nil), // 1: xray.proxy.whatsapp.Config
}
var file_proxy_whatsapp_config_proto_depIdxs = []int32{
	0, // 0: xray.proxy.whatsapp.Config.default_target:type_name -> xray.proxy.whatsapp.Target
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proxy_whatsapp_config_proto_init() }
func file_proxy_whatsapp_config_proto_init() {
	if File_proxy_whatsapp_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_whatsapp_config_proto_rawDesc), len(file_proxy_whatsapp_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_whatsapp_config_proto_goTypes,
		DependencyIndexes: file_proxy_whatsapp_config_proto_depIdxs,
		EnumInfos:         file_proxy_whatsapp_config_proto_enumTypes,
		MessageInfos:      file_proxy_whatsapp_config_proto_msgTypes,
	}.Build()
	File_proxy_whatsapp_config_proto = out.File
	file_proxy_whatsapp_config_proto_goTypes = nil
	file_proxy_whatsapp_config_proto_depIdxs = nil
}
