// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proxy/mtproto/config.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Secret                      string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Concurrency                 uint32                 `protobuf:"varint,2,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	AllowFallbackOnUnknownDc    bool                   `protobuf:"varint,3,opt,name=allow_fallback_on_unknown_dc,json=allowFallbackOnUnknownDc,proto3" json:"allow_fallback_on_unknown_dc,omitempty"`
	PreferIp                    string                 `protobuf:"bytes,4,opt,name=prefer_ip,json=preferIp,proto3" json:"prefer_ip,omitempty"`
	AutoUpdate                  bool                   `protobuf:"varint,5,opt,name=auto_update,json=autoUpdate,proto3" json:"auto_update,omitempty"`
	DomainFrontingPort          uint32                 `protobuf:"varint,6,opt,name=domain_fronting_port,json=domainFrontingPort,proto3" json:"domain_fronting_port,omitempty"`
	TolerateTimeSkewnessSeconds uint32                 `protobuf:"varint,7,opt,name=tolerate_time_skewness_seconds,json=tolerateTimeSkewnessSeconds,proto3" json:"tolerate_time_skewness_seconds,omitempty"`
	AntiReplay                  bool                   `protobuf:"varint,8,opt,name=anti_replay,json=antiReplay,proto3" json:"anti_replay,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_mtproto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mtproto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_mtproto_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Config) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *Config) GetAllowFallbackOnUnknownDc() bool {
	if x != nil {
		return x.AllowFallbackOnUnknownDc
	}
	return false
}

func (x *Config) GetPreferIp() string {
	if x != nil {
		return x.PreferIp
	}
	return ""
}

func (x *Config) GetAutoUpdate() bool {
	if x != nil {
		return x.AutoUpdate
	}
	return false
}

func (x *Config) GetDomainFrontingPort() uint32 {
	if x != nil {
		return x.DomainFrontingPort
	}
	return 0
}

func (x *Config) GetTolerateTimeSkewnessSeconds() uint32 {
	if x != nil {
		return x.TolerateTimeSkewnessSeconds
	}
	return 0
}

func (x *Config) GetAntiReplay() bool {
	if x != nil {
		return x.AntiReplay
	}
	return false
}

var File_proxy_mtproto_config_proto protoreflect.FileDescriptor

const file_proxy_mtproto_config_proto_rawDesc = "" +
	"\n" +
	"\x1aproxy/mtproto/config.proto\x12\x12xray.proxy.mtproto\"\xd8\x02\n" +
	"\x06Config\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12 \n" +
	"\vconcurrency\x18\x02 \x01(\rR\vconcurrency\x12>\n" +
	"\x1callow_fallback_on_unknown_dc\x18\x03 \x01(\bR\x18allowFallbackOnUnknownDc\x12\x1b\n" +
	"\tprefer_ip\x18\x04 \x01(\tR\bpreferIp\x12\x1f\n" +
	"\vauto_update\x18\x05 \x01(\bR\n" +
	"autoUpdate\x120\n" +
	"\x14domain_fronting_port\x18\x06 \x01(\rR\x12domainFrontingPort\x12C\n" +
	"\x1etolerate_time_skewness_seconds\x18\a \x01(\rR\x1btolerateTimeSkewnessSeconds\x12\x1f\n" +
	"\vanti_replay\x18\b \x01(\bR\n" +
	"antiReplayB)Z'github.com/xtls/xray-core/proxy/mtprotob\x06proto3"

var (
	file_proxy_mtproto_config_proto_rawDescOnce sync.Once
	file_proxy_mtproto_config_proto_rawDescData []byte
)

func file_proxy_mtproto_config_proto_rawDescGZIP() []byte {
	file_proxy_mtproto_config_proto_rawDescOnce.Do(func() {
		file_proxy_mtproto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mtproto_config_proto_rawDesc), len(file_proxy_mtproto_config_proto_rawDesc)))
	})
	return file_proxy_mtproto_config_proto_rawDescData
}

var file_proxy_mtproto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_mtproto_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.mtproto.Config
}
var file_proxy_mtproto_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_mtproto_config_proto_init() }
func file_proxy_mtproto_config_proto_init() {
	if File_proxy_mtproto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mtproto_config_proto_rawDesc), len(file_proxy_mtproto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mtproto_config_proto_goTypes,
		DependencyIndexes: file_proxy_mtproto_config_proto_depIdxs,
		MessageInfos:      file_proxy_mtproto_config_proto_msgTypes,
	}.Build()
	File_proxy_mtproto_config_proto = out.File
	file_proxy_mtproto_config_proto_goTypes = nil
	file_proxy_mtproto_config_proto_depIdxs = nil
}
